######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 22 19:34:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
